DROP TABLE IF EXISTS users, films, genre, ratings, friends, film_genre, popular_films, friendship_status CASCADE;

CREATE TABLE IF NOT EXISTS genre (
                                     genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name_genre varchar(15) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS ratings (
                                       rating_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       name_rating varchar(5) NOT NULL UNIQUE,
    description varchar(255)
    );

CREATE TABLE IF NOT EXISTS users (
                                     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email varchar(255) NOT NULL UNIQUE,
    login varchar(255) NOT NULL UNIQUE,
    name varchar(255),
    birthday date NOT NULL
    );

CREATE TABLE IF NOT EXISTS films (
                                     film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar(255) NOT NULL UNIQUE,
    description varchar(200),
    release_date date NOT NULL,
    duration int NOT NULL,
    rating_id int NOT NULL REFERENCES ratings (rating_id),
    count_likes int
    );

CREATE TABLE IF NOT EXISTS friends (
    user_id bigint REFERENCES users (user_id),
    friend_id bigint REFERENCES users (user_id),

    PRIMARY KEY (user_id, friend_id)
    );

CREATE TABLE IF NOT EXISTS film_genre (
    film_id bigint REFERENCES films (film_id),
    genre_id int REFERENCES genre (genre_id),
    PRIMARY KEY (film_id, genre_id)
    );

CREATE TABLE IF NOT EXISTS popular_films (
    film_id bigint REFERENCES films (film_id),
    user_id bigint REFERENCES users (user_id),
    PRIMARY KEY (film_id, user_id)
    );